### ISSUE TITLE
快速制作 Demo 仅包含前端页面和假数据

### ISSUE THREAD

**Issue by zzswang** [36node-lecha/vms-demo#1]
## 背景

客户在诸暨有个市政府项目，车辆管理系统，需要有一个展示型的页面

## 验收点

- 按照设计稿制作
- 按照给定的假数据，提供图表交互
- 地图引用高德或者百度地图，地图本身无需添加交互，只要可以放大缩小就行
- 多跨协同，用图片就行，有一些地方，没什么交互的话，也可以用切图

## 开发提示

- 使用 cra 快速初始化框架即可
- 会和设计师拉个群，切图有问题，需要直接和设计师沟通

![image](https://user-images.githubusercontent.com/1524745/144402627-dc2479dc-0a1d-407f-a808-1adcb52242c1.png)

**Comment by zzswang** [comment]
[公务车管理平台切图.zip](https://github.com/36node-lecha/vms-demo/files/7640957/default.zip)
[数据统计.xlsx](https://github.com/36node-lecha/vms-demo/files/7640958/default.xlsx)

**Comment by zzswang** [comment]
![image](https://user-images.githubusercontent.com/1524745/144411128-8c88d606-2d44-4515-ba7f-a3089caf9f3b.png)

这部分直接贴图就行

**Comment by zzswang** [comment]
## favico

![64-64](https://user-images.githubusercontent.com/1524745/144411341-e7ded949-dbad-4e45-a83a-5e74453e7b25.png)

**Comment by caicaishmily** [comment]
@zzswang  我已经尽力了  俊总  明天早上你先看一下  有些 UI 设计图上的效果实在不好弄  需要花时间搞   地图定位的那个  我也还没弄明白怎么圈起来
